server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.12.132
    username: supermall
    password: 123456
    virtual-host: /supermall
  redis:
    host: 192.168.12.132

sm:
  sms:
    accessKeyId: LTAIi6dIafoHGcp0
    accessKeySecret: qaAULfVidhsEeo4LJVlPqQxZSDbgPf
    signName: 乐优商城
    templateCode: SMS_171745552
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}