server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    auth-service: /auth/**
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    cart-service: /cart/**
    order-service: /order/**
    bid-service: /bid/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true #添加host头信息
  sensitive-headers:    #覆盖敏感头信息
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：10000ms
sm:
  jwt:
    pubKeyPath: E:/temp/rsa/id_rsa.pub # 公钥地址
    cookieName: SM_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/auth/*
      - /api/search/*
      - /zuul/api/upload/
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/user/query
      - /api/item
      - /api/order-service/order
      - /api/bid