server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.12.132:9001/supermall3
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 192.168.12.132
    username: supermall
    password: 123456
    virtual-host: /supermall
    template:
      exchange: sm.item.exchange #缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      retry: #失败重试
        enabled: true #开启失败重试
        initial-interval: 10000 #第一次重试的间隔时长
        max-interval: 30000 #最长重试间隔，超过这个间隔将不再重试
        multiplier: 2 #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
    publisher-confirms: true #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试\
    redis:
      host: 192.168.12.132
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  type-aliases-package: com.supermall.user.pojo

